### ISSUE TITLE
Code cleanup?

### ISSUE THREAD

**Issue by Christoph-Wagner** [howdy-tsc/LemmyTools#25]
I was wondering if you’d be interested in some code clean-up?

There are currently a few issues that make maintaining the code hard:

1. duplicate calls (e.g. Setting HTML in [Line 795](https://github.com/howdy-tsc/LemmyTools/blob/main/lemmyTools.js#L795) but again in [Line 92](https://github.com/howdy-tsc/LemmyTools/blob/main/lemmyTools.js#L92) from within a function call)
2. generally repeated code in different if-else branches
3. not clearly named variables
4. Very mixed indentation

This was a bit confusing when I submitted the PR for the community lists. If you prefer it that way, no sweat, just thought I’d post an issue to offer doing some clean-up ;)

If you would like that, two options:

1. A giant PR that mostly fixes all of those
2. several smaller PRs, one for indentation, one per function cleaned, etc.

In case I do that, it might also be best to coordinate that no major functionality work happens at the same time, I’d guess I could get through that in one day.

**Comment by howdy-tsc** [comment]
Hey, that's a really nice offer! I am admittedly a very much an amateur at all of this so my code is spaghetti and all my college computer science courses didn't stick because I never used them beyond my small amateur attempts at doing things. I write powershell and bash scripts normally!  I'm a sysadmin that is honestly just playing around. So, anyone that is used to this work like yourself I whole definitely welcome. I am however worried that if the code was "cleaned up" that I would just junk it up again due to being such an amateur and I would hate to waste someones time on that. So, currently I am a yes for your offer but I really would never want someone to waste their time and effort... If you did clean it up I would try my best to keep it in line with what you would provide. Alternatively, waiting for this to develop further may be of benefit before it is cleaned up as to not make it necessary again in the relatively short future. I am learning as I am going and I believe I am getting better with each iteration I am doing and I know I need to make it more readable to someone else.

Let me know your thoughts and thank you so very much.

**Comment by howdy-tsc** [comment]
I lied! I did a small commit this evening! Thank you for the communityArray join help. I was intending to figure out how to fix that... eventually. Viele danke!

**Comment by Christoph-Wagner** [comment]
Eh, I very much appreciate the work you have already done. I’m not one for maintaining or starting such projects :D 

The longer one waits, the harder it actually becomes. Even just incremental cleaning after a few weeks is far easier than figuring it out later ;) I should be pretty free on Sunday, so I’ll target that day for now :)

**Comment by Christoph-Wagner** [comment]
I was bored because the twitch stream I normally watch in the morning had technical issues, and so I started on this ;) The current version is here:
https://github.com/Christoph-Wagner/LemmyTools/blob/cleanup/lemmyTools.js

It is *very* buggy right now, something is going on with the animations that breaks things (honestly, CSS animations are not something I ever understood how to use :D), and none of the sidebar things work properly. But this version now has proper scripts instead of strings added to the document (I’m guessing there’s some permission issue that’s wreaking havoc because of that), which already allowed my IDE to find several issues automatically.

**Comment by howdy-tsc** [comment]
Hey that's awesome. I'll check this out when I'm home later or tomorrow. I was just about to push an update later today but I might wait. I wrote an open all images button (or setting) that lots of people have been asking about. I'm excited to see what you've done. Thank you.

**Comment by howdy-tsc** [comment]
@Christoph-Wagner THIS IS SO GREAT! THANK YOU. I got to take a look at it tonight. Very cool! I am not going to push anything for the next few days so please feel free to do your thing if you feel like it and then we can work on taking it back together and runnign with. Don't worry, I can handle the CSS. I know you could figure it out if you wanted to learn. It is confusing because there isn't any logical code to follow. 

I did push 0.1.2.7 that added some new features tonight. Hope that wasn't a problem. No more from me for a few days. Thanks again.

**Comment by Christoph-Wagner** [comment]
Everything but search seems to be working, once that does, I’ll need to do some testing of all the features. Then I’ll add your last change. 

I’m making lunch now, should be able to finish everything later today. Feel free to look through the code if there’s anything that’s not clear to you.

**Comment by howdy-tsc** [comment]
Looking good! I am going to really dive into it later this evening or tomorrow to try and understand. It appears to be working and you are doing things in much more efficient and "smarter" ways than I was. And to be honest, teaching me a ton! Getting rid of the `` blocks is so much easier. It's going to take me a bit to understand everything but It's fantastic and much clearer code. 

This is the first time I've ever collaborated with someone on anything I've done and I truly appreciate you. 

More to come when I get some time to "digest" this code!

**Comment by howdy-tsc** [comment]
Closing issue.
