### ISSUE TITLE
[Layout] Sidebar overlaps content with old.Reddit Re-format enabled

### ISSUE THREAD

**Issue by datWeazel** [howdy-tsc/LemmyTools#33]
I have the LemmyTools sidebar on the right and the Re-format enabled and the elements on the right (e.G. my Username or the sidebar of my instance) are behind the LemmyTools sidebar. That way I can't read stuff thats there. Maybe add a margin on the right if Re-format is enabled?

**Comment by howdy-tsc** [comment]
[I confirm the issue however this is sort of expected](https://pixelfed.social/storage/m/_v2/581914529167854145/bf0f52ff2-92677b/BcfuuJb2G72P/G9ZrN8Zigc3DI8wDgxbrWKjLE9aQVIx0U3ReRKWi.png?v=1688733637). You must have the option of "Keep LemmyTools Bar Open" checked. Otherwise it should collapse into a [small tab](https://thesimplecorner.org/pictrs/image/aec88485-377c-4e67-85e5-1df231aec358.png) that shouldn't be getting in your way unless you are hovering over the area. You can also adjust the vertical position to get it away from say the "login" button 5% does good with that.

So try some of those options. You could also remove the lemmy ui sidebar elements but that stops you from using them as well.

In the future, I am wanting to add a top window option for the sidebar like how reddit used to have that would also fix your issue.

**Comment by datWeazel** [comment]
What I meant was, that the sidebar overlaps even if collapsed. So some elements are always hidden no matter what.

**Comment by howdy-tsc** [comment]
Could you provide a screenshot of possible?

**Comment by datWeazel** [comment]
There you go. As you can see, even tho the sidebar is collapsed, some elements are cutoff. It's not that dramatic, but a bit annoying nonetheless. 
 
I only have this problem on a 1080p display. On my 1440p screen there's no overlap since there is more space on both sides.

![Screenshot_20230709_181353](https://github.com/howdy-tsc/LemmyTools/assets/3285115/d5ebc435-6d5a-4e76-8688-84396daf2fa6)
![Screenshot_20230709_181434](https://github.com/howdy-tsc/LemmyTools/assets/3285115/3e4b8283-02ea-4ecc-9f77-84c15e60f3f6)

**Comment by rcmaehl** [comment]
Issue also occurs for people using a Portrait (e.g. 900x1440) screen for reading

![image](https://github.com/howdy-tsc/LemmyTools/assets/716581/84186a5f-c186-46ab-bd3b-eca427ad29ef)

**Comment by howdy-tsc** [comment]
Gotcha, that is very helpful. Next update 0.2.0.2 will provide a smaller tab. Don't forget you can reposition it to either side and vertically.

**Comment by howdy-tsc** [comment]
sub 1200 width desktop will have this.
![](https://pixelfed.social/storage/m/_v2/581914529167854145/bf0f52ff2-92677b/R66e2tXCj5Qr/LRwIDYCwdUXvPEqEcPp8cyqAF1s4avcLyrJedhaI.png)
![](https://pixelfed.social/storage/m/_v2/581914529167854145/bf0f52ff2-92677b/AaI9NmCYS4vb/CnL0NuXIBzrXHmJurFgNhcRgIMGw6mrda1ljvFlf.png)

**Comment by howdy-tsc** [comment]
With top bar and the adjustment I made. I am closing this. Thank you.
